---
project-template:
- required:
  - name: name
    fieldtype: text
    required: true
  - name: metapath
    fieldtype: text
    required: true
    value: "Projects"
  - name: namespace
    fieldtype: text
    required: true
    value: "we1sv2.0"
  - name: title
    fieldtype: text
    required: true
  - name: resources
    fieldtype: textarea
    required: true
    skip: true
    placeholder: "List each resource on a separate line. Use the format 'type: mongodb-query'."
  - name: contributors
    fieldtype: textarea
    required: true
    placeholder: List each contributor on a separate line. Use the format 'title, path, email, role, group, organization' (in that order). Only the title property is required.
    cols: ['title']
  - name: created
    fieldtype: textarea
    required: true
    placeholder: List each date on a separate line. Date ranges should separate start and end dates with commas. Valid formats are YYYY-MM-DD and YYYY-MM-DDTHH:MM:SS.
    cols: ['start']
- optional:
  - name: id
    fieldtype: text
  - name: _id
    fieldtype: text
  - name: description
    fieldtype: textarea
  - name: version
    fieldtype: text
  - name: shortTitle
    fieldtype: text
  - name: label
    fieldtype: text
  - name: notes
    placeholder: Click the (+) button to add more notes.
    fieldtype: textarea
  - name: keywords
    fieldtype: text
    placeholder: Separate multiple keywords with commas.
  - name: image
    fieldtype: text
  - name: updated
    fieldtype: textarea
    placeholder: List each date on a separate line. Date ranges should separate start and end dates with commas. Valid formats are YYYY-MM-DD and YYYY-MM-DDTHH:MM:SS.
  - name: licenses
    fieldtype: textarea
    placeholder: List each license on a separate line. Use the format 'name, path, title' (in that order). At least one of properties name or path is required.
  - name: format
    fieldtype: textarea
